version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.7.0
    working_directory: ~/repo

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci

  build-ex-item:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build the project
          command: npx nx build ex-item

  build-ex-shared:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build the project
          command: npx nx build ex-shared


  build-ex-uer:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build the project
          command: npx nx build ex-user

  test-ex-item:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npx nx test ex-item

  test-ex-shared:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npx nx test ex-shared

  test-ex-user:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npx nx test ex-user

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build-ex-item
      - build-ex-shared
      - build-ex-user
      - test-ex-item
      - test-ex-shared
      - test-ex-user
