version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18.0
    working_directory: ~/repo

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build the project
          command: npx nx build nx-circle-ci-example

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npx nx test nx-circle-ci-example

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build
      - test
